use aula7exer2evolucao3;

DROP TABLE IF EXISTS PERFUME;
DROP TABLE IF EXISTS telefone;
DROP TABLE IF EXISTS medicamentos;
DROP TABLE IF EXISTS comercializa;
DROP TABLE IF EXISTS prescreve;
DROP TABLE IF EXISTS MEDICAMENTO;
DROP TABLE IF EXISTS PRODUTO;
DROP TABLE IF EXISTS FABRICANTE;
DROP TABLE IF EXISTS RECEITA;
DROP TABLE IF EXISTS VENDA;
DROP TABLE IF EXISTS CLIENTE;